# Generated by Django 5.2.13 on 2026-04-21 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_offers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='users.recruiter'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['recruiter', '-created_at'], name='job_offers__recruit_1f9272_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['location'], name='job_offers__locatio_a67ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['-created_at'], name='job_offers__created_a93edb_idx'),
        ),
    ]
