# Generated by Django 4.2.16 on 2026-10-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paused', 'Paused'), ('closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['recruiter', 'status'], name='job_offers__recruit_1bd4c2_idx'),
        ),
    ]
