# Generated by Django 4.2.16 on 2026-10-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0003_joboffer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=12),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='experience_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='nice_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='screening_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
