# Generated by Django 4.2.16 on 2026-10-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0004_joboffer_wizard_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
