# Generated by Django 5.2.13 on 2026-04-21 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
        ('job_offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='job_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='job_offers.joboffer'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.questionset'),
        ),
        migrations.AddField(
            model_name='interview',
            name='question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='interviews.questionset'),
        ),
        migrations.AddIndex(
            model_name='questionset',
            index=models.Index(fields=['job_offer', 'status'], name='interviews__job_off_e1c816_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionset',
            unique_together={('job_offer', 'version')},
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('interview__isnull', True), ('question_set__isnull', False)), models.Q(('interview__isnull', False), ('question_set__isnull', True)), _connector='OR'), name='question_source_xor'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['status'], name='interviews__status_187f27_idx'),
        ),
    ]
