# Generated by Django 5.1.6 on 2025-03-09 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='candidate_audio',
        ),
        migrations.AddField(
            model_name='answer',
            name='candidate_video',
            field=models.FileField(blank=True, null=True, upload_to='interview_videos/'),
        ),
        migrations.AddField(
            model_name='answer',
            name='interview',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interviews.interview'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_date',
            field=models.DateTimeField(default='19/03/2002'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
