# Generated by Django 5.1.6 on 2025-03-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_remove_answer_candidate_audio_answer_candidate_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
