# Generated by Django 5.2.13 on 2026-04-21 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('job_offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_offers.joboffer'),
        ),
    ]
