# Generated by Django 5.2.13 on 2026-04-21 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('interviews', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobseeker'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.interview'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.recruiter'),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='users.jobseeker'),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.resume'),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed', to='applications.resume'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['job_seeker', 'is_default'], name='application_job_see_8dfc3e_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_1508e0_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'job_offer'], name='application_status_e1d327_idx'),
        ),
    ]
