# Generated by Django 4.2.16 on 2026-10-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
    ]
