# Generated by Django 5.1.6 on 2025-02-23 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_interview_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='application',
        ),
    ]
