# Generated by Django 5.1.6 on 2025-02-23 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_interview_application'),
        ('core', '0008_remove_question_interview_delete_answer_and_more'),
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.interview'),
        ),
        migrations.AddField(
            model_name='application',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
