/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: {
          base:            '#090C14',
          surface:         '#101420',
          elevated:        '#181E2E',
          border:          '#232A3E',
          accent:          '#F59E0B',
          'accent-hover':  '#D97706',
          'accent-muted':  '#2D2108',
          'accent-bright': '#FCD34D',
          'text-primary':  '#EEF0F8',
          'text-muted':    '#9BA6C4',
          'text-disabled': '#59628A',
          violet:          '#7C3AED',
          'violet-muted':  '#3D1F7A',
          // Semantic status colors used in badges
          success:  '#10B981',
          warning:  '#F59E0B',
          error:    '#EF4444',
        },
        // Light-mode surface variants
        'surface-light':  '#F8FAFC',
        'surface-border': '#E2E8F0',
      },
      backdropBlur: {
        glass: '12px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'Courier New', 'monospace'],
      },
      animation: {
        'spin-slow': 'spin 3s linear infinite',
      },
      boxShadow: {
        'card':        '0 1px 3px 0 rgba(0,0,0,0.5), 0 1px 2px -1px rgba(0,0,0,0.5)',
        'elevated':    '0 10px 30px -10px rgba(0,0,0,0.7)',
        'glow':        '0 0 24px -4px rgba(245,158,11,0.45)',
        'glow-sm':     '0 0 12px -3px rgba(245,158,11,0.35)',
        'glow-lg':     '0 0 60px -8px rgba(245,158,11,0.55)',
        'glow-amber':  '0 0 40px rgba(245,158,11,0.2)',
        'inner-top':   'inset 0 1px 0 rgba(255,255,255,0.06)',
        'card-3d':     '0 40px 120px -20px rgba(0,0,0,0.9), 0 0 0 1px rgba(255,255,255,0.05)',
        'violet-glow': '0 0 40px -5px rgba(124,58,237,0.45)',
        'card-light':  '0 1px 3px 0 rgba(0,0,0,0.08), 0 1px 2px -1px rgba(0,0,0,0.06)',
      },
      animation: {
        'fadeIn':       'fadeIn 0.5s cubic-bezier(0.16,1,0.3,1)',
        'slideUp':      'slideUp 0.6s cubic-bezier(0.16,1,0.3,1)',
        'slideDown':    'slideDown 0.25s ease-out',
        'toast-in':     'toastIn 0.35s cubic-bezier(0.34,1.56,0.64,1)',
        'toast-out':    'toastOut 0.25s ease-in forwards',
        'skeleton':     'skeleton 1.6s ease-in-out infinite',
        'spin-slow':    'spin 2s linear infinite',
        'float':        'float 8s ease-in-out infinite',
        'float-slow':   'float 13s ease-in-out infinite 1s',
        'float-fast':   'float 5s ease-in-out infinite 0.3s',
        'shimmer':      'shimmer 3s linear infinite',
        'glow-pulse':   'glowPulse 3s ease-in-out infinite',
        'marquee':      'marquee 35s linear infinite',
        'slide-in-l':   'slideInLeft 0.5s cubic-bezier(0.16,1,0.3,1)',
        'tilt-in':      'tiltIn 0.8s cubic-bezier(0.16,1,0.3,1)',
        'scale-in':     'scaleIn 0.5s cubic-bezier(0.16,1,0.3,1)',
        'orb-drift':    'orbDrift 20s ease-in-out infinite',
        'orb-drift-r':  'orbDriftR 25s ease-in-out infinite 3s',
        'grid-scroll':  'gridScroll 12s linear infinite',
      },
      keyframes: {
        fadeIn:      { from: { opacity: 0, transform: 'translateY(14px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        slideUp:     { from: { opacity: 0, transform: 'translateY(32px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        slideDown:   { from: { opacity: 0, transform: 'translateY(-10px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        toastIn:     { from: { opacity: 0, transform: 'translateX(100%) scale(0.95)' }, to: { opacity: 1, transform: 'translateX(0) scale(1)' } },
        toastOut:    { from: { opacity: 1, transform: 'translateX(0) scale(1)' }, to: { opacity: 0, transform: 'translateX(100%) scale(0.95)' } },
        skeleton:    { '0%, 100%': { opacity: 0.4 }, '50%': { opacity: 1 } },
        float:       { '0%,100%': { transform: 'translateY(0px) rotate(0deg)' }, '40%': { transform: 'translateY(-22px) rotate(1.5deg)' }, '70%': { transform: 'translateY(-10px) rotate(-1deg)' } },
        shimmer:     { '0%': { backgroundPosition: '-400% center' }, '100%': { backgroundPosition: '400% center' } },
        glowPulse:   { '0%,100%': { opacity: 0.35 }, '50%': { opacity: 0.85 } },
        marquee:     { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-50%)' } },
        slideInLeft: { from: { opacity: 0, transform: 'translateX(-24px)' }, to: { opacity: 1, transform: 'translateX(0)' } },
        tiltIn:      { from: { opacity: 0, transform: 'perspective(1200px) rotateX(10deg) translateY(35px) scale(0.97)' }, to: { opacity: 1, transform: 'perspective(1200px) rotateX(0deg) translateY(0) scale(1)' } },
        scaleIn:     { from: { opacity: 0, transform: 'scale(0.9)' }, to: { opacity: 1, transform: 'scale(1)' } },
        orbDrift:    { '0%,100%': { transform: 'translate(0px, 0px) scale(1)' }, '33%': { transform: 'translate(40px, -30px) scale(1.1)' }, '66%': { transform: 'translate(-20px, 15px) scale(0.9)' } },
        orbDriftR:   { '0%,100%': { transform: 'translate(0px, 0px) scale(1)' }, '33%': { transform: 'translate(-50px, 20px) scale(0.95)' }, '66%': { transform: 'translate(30px, -40px) scale(1.08)' } },
        gridScroll:  { '0%': { backgroundPosition: '0 0' }, '100%': { backgroundPosition: '60px 60px' } },
      },
    },
  },
  plugins: [],
};
