# Generated by Django 5.2.13 on 2026-04-21 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_score', models.FloatField()),
                ('analysis_details', models.JSONField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_analysis', to='applications.application')),
            ],
        ),
    ]
