# Generated by Django 4.2.16 on 2024-11-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application_interview_role_remove_user_is_job_seeker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
