# Generated by Django 4.2.16 on 2024-11-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recruiter_company_website_recruiter_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
