# Generated by Django 4.2.16 on 2024-12-25 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('core', '0004_alter_recruiter_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='job_offer',
        ),
        migrations.RemoveField(
            model_name='application',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='recruiter',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AlterField(
            model_name='cvanalysis',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.application'),
        ),
    ]
