# Generated by Django 4.2.16 on 2024-12-25 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_initial'),
        ('users', '0001_initial'),
        ('core', '0005_remove_application_job_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.recruiter'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='JobOffer',
        ),
        migrations.DeleteModel(
            name='JobSeeker',
        ),
        migrations.DeleteModel(
            name='Recruiter',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
