# Generated by Django 5.1.5 on 2025-01-22 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_interview_feedback'),
        ('core', '0006_alter_feedback_recruiter_alter_interview_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='application',
        ),
        migrations.AlterField(
            model_name='question',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.interview'),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
